Repository sealsystems/node-ipp, pull requests merged in 2019-10, with the labels that each got.

#36 chore: Fixed error parsing CUPS operations
  lib/parser.js
  test/lib/parserTest.js
Labels: release/chore, release/patch

#39 fix: Fixed bugs
  README.md
  lib/parser.js
  lib/serializer.js
  test/lib/parserTest.js
Labels: release/fix, release/patch

#43 fix: Added attribute 'notify-wait'
  lib/attributes.js
Labels: release/fix, release/patch

#44 chore: Use semantic release without roboter
  .circleci/config.yml
  .eslintrc
  .github/pull_request_template.md
  .gitignore
  .npmignore
  .vscode/launch.json
  appveyor.yml
  examples/Get-Job-Attributes.js
  examples/Get-Jobs.js
  examples/Get-Printer-Attributes.js
  examples/Get-Printer-Attributes2.js
  examples/Identify-Printer.js
  examples/Print-URI.js
  examples/findPrinters.js.off
  examples/printPDF.js
  ipp.js
  lib/StreamParser.js
  lib/attributes.js
  lib/enums.js
  lib/isReadableStream.js
  lib/keywords.js
  lib/parser.js
  lib/printer.js
  lib/serializer.js
  package-lock.json
  package.json
  roboter.js
  test/lib/StreamParserTest.js
  test/lib/parserTest.js
  test/lib/requestTest.js
  test/lib/serializerTest.js
  test/mocha.opts
Labels: release/chore, release/patch

#46 fix: Notify missings
  lib/attributes.js
  lib/serializer.js
Labels: release/fix, release/patch

#47 feat: Included SEAL Systems specific operation attributes
  README.md
Labels: release/feat, release/minor
